# Generated by Django 5.2.6 on 2025-09-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='review_text',
            new_name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='cons',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='extra_input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='product_name',
            field=models.CharField(default='default_product', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='pros',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='default_title', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
